### ISSUE TITLE
Making float window center and adjusting width and height with lua

### ISSUE THREAD

**Issue by kkharji** [conweller/findr.vim#20] opened 2020-10-21 21:30 UTC
hey there, 

First of all I'm glad I found this plugin, it works amazing and it brought back something I missed from emacs. Thanks a lot!!

I'm trying to set the location, height and width of findr popup to my fzf.vim setup. Center and with the following settings

```
  vim.g.findr_floating_window = {
    window = {
      width   = 0.75,
      height = 0.66,
      yoffset = 0.5,
      xoffset = 0.5,
    }
  }

```
Error: lua ...site/pack/packer/opt/findr.vim/lua/findr/view/window.lua:23: Expected lua string

Thanks again

**Comment by conweller** [comment] 2020-10-22 20:34
That's awesome you like it!

It looks like I'm getting the same error you are, I'll try to get that fixed in the day or so

**Comment by kkharji** [comment] 2020-10-23 00:03
Thanks a lot @conweller . Also it would be nice for new comers that the floating window is centered exactly in the middle of the screen, this not my place to say as current position might preferable by you.

**Comment by conweller** [comment] 2020-10-23 23:06
Ok so right now the issue is that `findr_floating_window.window` expects a VimL expression string which is evaluated with `vim.fn.eval`, not a variable.

You should be able to center the window with this vimscript (changing `max_heigth` and `max_width` to whatever you want):

``` vim
let g:findr_floating_window = {
      \ 'window': 'FindrFloatingWindow()'
      \ }

function! FindrFloatingWindow()
  let [max_height, max_width] = [20, 100]
  let height = min([&lines - 4, max_height])
  let width = min([&columns - 4, max_width])
  return {
       \ 'relative': 'editor',
       \ 'col': float2nr((&columns - width)/2),
       \ 'row': float2nr((&lines - height)/2),
       \ 'height': height,
       \ 'width': width,
       \ 'style': 'minimal',
       \ }
endfunction
```

Or if you want to do it in lua, here's a workaround:

``` lua
function findr_winopts()
  local max_height, max_width = 20, 100
  local height = math.min(vim.o.lines - 4, max_height)
  local width = math.min(vim.o.columns - 4, max_width)
  local opts = {
    relative= 'editor',
    height = height,
    width = width,
    col = math.floor( (vim.o.columns - width) / 2 ),
    row = math.floor( (vim.o.lines - height) / 2 ),
    style= 'minimal',
  }
  return opts
end

vim.g.findr_floating_window = {
  window = [[luaeval("findr_winopts()")]],
}
```

**Comment by conweller** [comment] 2020-10-23 23:36
I definitely would like to change the interface to allow for easier customization via lua, but it seems somewhat complicated to do so. In neovim, at least as of right now, you can't set `vim.g.*` variables to lua functions, so I'm not entirely what the best way to allow for lua and vimL configuration.

**Comment by conweller** [comment] 2020-10-23 23:38
Also just added an option to center the window by just setting the following:

```vim
let g:findr_floating_window = {'position' : 'center'}
```

Or in lua:

``` lua
vim.g.findr_floating_window = {position= 'center'}
```

**Closed as completed** 2020-10-23 23:39 UTC

**Comment by kkharji** [comment] 2020-10-23 23:52
@conweller thanks a lot for solving my issue, I appreciate it .

**Comment by conweller** [comment] 2020-10-24 00:42
You're welcome!
